Repository NorseBooks/NorseBooks, pull requests merged in 2021-08, with the labels that each got.

#1 Add favicon
  app/src/app/app.component.html
  app/src/assets/img/logo.png
  app/src/favicon.ico
Labels: frontend

#2 set site theme colors
  app/src/app/app.component.html
  app/src/app/app.module.ts
  app/src/styles.scss
Labels: enhancement, frontend

#4 Add useful info to README
  README.md
  app/README.md
Labels: enhancement

#3 Initialize database and implement database interaction service
  package-lock.json
  package.json
  src/app.module.ts
  src/db/db.service.spec.ts
  src/db/db.service.ts
  src/sql/init/NB_BOOK.sql
  src/sql/init/NB_BOOK_CONDITION.sql
  src/sql/init/NB_DEPARTMENT.sql
  src/sql/init/NB_FEEDBACK.sql
  src/sql/init/NB_IMAGE.sql
  src/sql/init/NB_MESSAGE.sql
  src/sql/init/NB_PASSWORD_RESET.sql
  src/sql/init/NB_REFERRAL.sql
  src/sql/init/NB_REPORT.sql
  src/sql/init/NB_RESOURCE.sql
  src/sql/init/NB_SEARCH_SORT.sql
  src/sql/init/NB_SESSION.sql
  src/sql/init/NB_USER.sql
  src/sql/init/NB_USER_INTEREST.sql
  src/sql/init/NB_VERIFY.sql
  src/tables/NB_BOOK_CONDITION.csv
  src/tables/NB_DEPARTMENT.csv
  src/tables/NB_SEARCH_SORT.csv
Labels: enhancement, backend, database

#6 Redirect HTTP to HTTPS
  package-lock.json
  package.json
  src/main.ts
Labels: enhancement, backend

#7 Add cookie parsing
  package-lock.json
  package.json
  src/app.module.ts
  src/decorators/cookie.decorator.ts
  src/main.ts
  src/services/db/db.service.spec.ts
  src/services/db/db.service.ts
  src/sql/tables/NB_BOOK_CONDITION.csv
  src/sql/tables/NB_DEPARTMENT.csv
  src/sql/tables/NB_SEARCH_SORT.csv
Labels: enhancement, backend

#8 First six backend services
  package-lock.json
  package.json
  src/app.module.ts
  src/services/db/db.service.ts
  src/services/image/image.interface.ts
  src/services/image/image.service.spec.ts
  src/services/image/image.service.ts
  src/services/password-reset/password-reset.interface.ts
  src/services/password-reset/password-reset.service.spec.ts
  src/services/password-reset/password-reset.service.ts
  src/services/resource/resource.interface.ts
  src/services/resource/resource.service.spec.ts
  src/services/resource/resource.service.ts
  src/services/service.exception.ts
  src/services/session/session.interface.ts
  src/services/session/session.service.spec.ts
  src/services/session/session.service.ts
  src/services/user/user.interface.ts
  src/services/user/user.service.spec.ts
  src/services/user/user.service.ts
  src/services/verify/verify.interface.ts
  src/services/verify/verify.service.spec.ts
  src/services/verify/verify.service.ts
  src/sql/init/NB_RESOURCE.sql
  src/sql/tables/NB_RESOURCE.csv
Labels: enhancement, backend

#9 Prune database records
  src/services/db/db.service.ts
  src/services/image/image.service.ts
  src/services/password-reset/password-reset.service.ts
  src/services/resource/resource.service.ts
  src/services/session/session.service.ts
  src/services/user/user.service.ts
  src/services/verify/verify.service.ts
  src/sql/tables/NB_RESOURCE.csv
Labels: backend

#10 User session decorator and guards
  src/app.controller.ts
  src/decorators/user-session.decorator.ts
  src/guards/user-session-optional.guard.ts
  src/guards/user-session-required.guard.ts
Labels: backend

#11 Parse postgres money type to float
  src/services/db/db.service.ts
Labels: backend, database

#12 Test database
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/main.ts
  src/services/db/db.service.spec.ts
  src/services/db/db.service.ts
  src/services/image/image.service.spec.ts
  src/services/image/image.service.ts
  src/services/password-reset/password-reset.service.spec.ts
  src/services/password-reset/password-reset.service.ts
  src/services/resource/resource.service.spec.ts
  src/services/session/session.service.spec.ts
  src/services/session/session.service.ts
  src/services/test-util.ts
  src/services/user/user.service.spec.ts
  src/services/user/user.service.ts
  src/services/verify/verify.service.spec.ts
  src/services/verify/verify.service.ts
Labels: testing

#13 First tests
  .gitignore
  jest.config.ts
  package.json
  src/services/db/db.service.spec.ts
  src/services/db/db.service.ts
  src/services/image/image.service.spec.ts
  src/services/password-reset/password-reset.service.spec.ts
  src/services/resource/resource.service.spec.ts
  src/services/session/session.service.spec.ts
  src/services/test-setup.ts
  src/services/test-util.ts
  src/services/user/user.service.spec.ts
  src/services/verify/verify.service.spec.ts
Labels: testing

#15 Department and book condition services and tests
  src/app.module.ts
  src/services/book-condition/book-condition.interface.ts
  src/services/book-condition/book-condition.service.spec.ts
  src/services/book-condition/book-condition.service.ts
  src/services/db/db.service.spec.ts
  src/services/department/department.interface.ts
  src/services/department/department.service.spec.ts
  src/services/department/department.service.ts
  src/services/image/image.service.spec.ts
  src/services/password-reset/password-reset.service.spec.ts
  src/services/resource/resource.service.spec.ts
  src/services/session/session.service.spec.ts
  src/services/test-util.ts
  src/services/user/user.service.spec.ts
  src/services/verify/verify.service.spec.ts
Labels: backend, testing

#19 Show coverage badges in README
  .gitignore
  README.md
  coverage/badge-branches.svg
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  package.json
Labels: enhancement

#16 Book and report services/tests
  src/app.module.ts
  src/services/book/book.interface.ts
  src/services/book/book.service.spec.ts
  src/services/book/book.service.ts
  src/services/report/report.interface.ts
  src/services/report/report.service.spec.ts
  src/services/report/report.service.ts
  src/services/session/session.service.ts
  src/services/test-util.ts
  src/services/user/user.service.spec.ts
  src/services/user/user.service.ts
  src/sql/init/NB_BOOK.sql
  src/sql/tables/NB_RESOURCE.csv
Labels: backend, testing

#17 Message, SearchSort, and Feedback services/tests
  src/app.module.ts
  src/services/feedback/feedback.interface.ts
  src/services/feedback/feedback.service.spec.ts
  src/services/feedback/feedback.service.ts
  src/services/message/message.interface.ts
  src/services/message/message.service.spec.ts
  src/services/message/message.service.ts
  src/services/search-sort/search-sort.interface.ts
  src/services/search-sort/search-sort.service.spec.ts
  src/services/search-sort/search-sort.service.ts
  src/services/test-util.ts
  src/sql/tables/NB_RESOURCE.csv
  src/sql/tables/NB_SEARCH_SORT.csv
Labels: backend, testing

#18 User Interest and Referral services/tests
  src/app.module.ts
  src/services/referral/referral.interface.ts
  src/services/referral/referral.service.spec.ts
  src/services/referral/referral.service.ts
  src/services/test-util.ts
  src/services/user-interest/user-interest.interface.ts
  src/services/user-interest/user-interest.service.spec.ts
  src/services/user-interest/user-interest.service.ts
  src/sql/init/NB_REFERRAL.sql
  src/sql/init/NB_USER_INTEREST.sql
  src/sql/tables/NB_RESOURCE.csv
Labels: backend, testing

#21 Book searching
  coverage/badge-branches.svg
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/services/book/book.service.spec.ts
  src/services/book/book.service.ts
Labels: backend, testing

#22 Check user and book image deletion
  src/services/book/book.service.spec.ts
  src/services/user/user.service.spec.ts
Labels: testing

#23 Remove tests checking if service is defined
  src/services/book-condition/book-condition.service.spec.ts
  src/services/book/book.service.spec.ts
  src/services/db/db.service.spec.ts
  src/services/department/department.service.spec.ts
  src/services/feedback/feedback.service.spec.ts
  src/services/image/image.service.spec.ts
  src/services/message/message.service.spec.ts
  src/services/password-reset/password-reset.service.spec.ts
  src/services/referral/referral.service.spec.ts
  src/services/report/report.service.spec.ts
  src/services/resource/resource.service.spec.ts
  src/services/search-sort/search-sort.service.spec.ts
  src/services/session/session.service.spec.ts
  src/services/user-interest/user-interest.service.spec.ts
  src/services/user/user.service.spec.ts
  src/services/verify/verify.service.spec.ts
Labels: testing

#24 Check boolean values in tests explicitly
  src/services/book-condition/book-condition.service.spec.ts
  src/services/book/book.service.spec.ts
  src/services/department/department.service.spec.ts
  src/services/feedback/feedback.service.spec.ts
  src/services/image/image.service.spec.ts
  src/services/message/message.service.spec.ts
  src/services/password-reset/password-reset.service.spec.ts
  src/services/referral/referral.service.spec.ts
  src/services/report/report.service.spec.ts
  src/services/resource/resource.service.spec.ts
  src/services/search-sort/search-sort.service.spec.ts
  src/services/session/session.service.spec.ts
  src/services/user-interest/user-interest.service.spec.ts
  src/services/user/user.service.spec.ts
  src/services/verify/verify.service.spec.ts
Labels: testing

#28 Improve coverage
  coverage/badge-branches.svg
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/services/book/book.service.spec.ts
  src/services/book/book.service.ts
  src/services/db/db.service.spec.ts
  src/services/feedback/feedback.service.spec.ts
  src/services/image/image.service.spec.ts
  src/services/message/message.service.spec.ts
  src/services/password-reset/password-reset.service.spec.ts
  src/services/password-reset/password-reset.service.ts
  src/services/referral/referral.service.spec.ts
  src/services/report/report.service.spec.ts
  src/services/resource/resource.interface.ts
  src/services/resource/resource.service.spec.ts
  src/services/resource/resource.service.ts
  src/services/session/session.service.spec.ts
  src/services/user-interest/user-interest.service.spec.ts
  src/services/user/user.service.spec.ts
  src/services/user/user.service.ts
  src/services/verify/verify.service.spec.ts
  src/sql/tables/NB_RESOURCE.csv
Labels: enhancement, testing

#29 Database backup
  .gitignore
  package.json
  requirements.txt
  scripts/backup.py
  src/backup.ts
  src/main.ts
Labels: enhancement, database

#32 Resource and image controllers
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/controllers/image/image.controller.spec.ts
  src/controllers/image/image.controller.ts
  src/controllers/resource/resource.controller.spec.ts
  src/controllers/resource/resource.controller.ts
  src/decorators/query-boolean.decorator.ts
  src/decorators/query-number.decorator.ts
  src/decorators/query-string.decorator.ts
  src/decorators/user-session.decorator.ts
  src/guards/admin.guard.ts
  src/guards/session-optional.guard.ts
  src/guards/session-required.guard.ts
  src/interceptors/response.interceptor.ts
Labels: backend

#33 User controller
  src/app.module.ts
  src/controllers/user/user.controller.spec.ts
  src/controllers/user/user.controller.ts
Labels: backend

#34 Use request body for image data
  src/controllers/user/user.controller.ts
  src/decorators/body-boolean.decorator.ts
  src/decorators/body-number.decorator.ts
  src/decorators/body-string.decorator.ts
Labels: bug, backend

#35 Set up emailing and design emails
  package-lock.json
  package.json
  src/controllers/user/user.controller.ts
  src/decorators/cookie.decorator.ts
  src/decorators/hostname.decorator.ts
  src/emailer.ts
  src/emails/password-reset.html
  src/emails/password-reset.txt
  src/emails/verify.html
  src/emails/verify.txt
Labels: enhancement, backend
