Repository NorseBooks/NorseBooks, pull requests merged in 2021-09, with the labels that each got.

#36 Verify and Password Reset controllers
  src/app.module.ts
  src/controllers/password-reset/password-reset.controller.spec.ts
  src/controllers/password-reset/password-reset.controller.ts
  src/controllers/verify/verify.controller.spec.ts
  src/controllers/verify/verify.controller.ts
Labels: backend

#37 Department and Book Condition controllers
  src/app.module.ts
  src/controllers/book-condition/book-condition.controller.spec.ts
  src/controllers/book-condition/book-condition.controller.ts
  src/controllers/department/department.controller.spec.ts
  src/controllers/department/department.controller.ts
  src/controllers/password-reset/password-reset.controller.ts
  src/services/department/department.service.ts
Labels: backend

#39 Message and Search Sort controllers
  coverage/badge-branches.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/app.module.ts
  src/controllers/message/message.controller.spec.ts
  src/controllers/message/message.controller.ts
  src/controllers/search-sort/search-sort.controller.spec.ts
  src/controllers/search-sort/search-sort.controller.ts
  src/services/message/message.service.spec.ts
  src/services/message/message.service.ts
Labels: backend

#40 Feedback, User Interest, and Referral controllers
  coverage/badge-branches.svg
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/app.module.ts
  src/controllers/feedback/feedback.controller.spec.ts
  src/controllers/feedback/feedback.controller.ts
  src/controllers/referral/referral.controller.spec.ts
  src/controllers/referral/referral.controller.ts
  src/controllers/user-interest/user-interest.controller.spec.ts
  src/controllers/user-interest/user-interest.controller.ts
  src/services/feedback/feedback.service.spec.ts
  src/services/feedback/feedback.service.ts
  src/services/referral/referral.service.spec.ts
  src/services/referral/referral.service.ts
Labels: backend

#43 API service
  app/src/app/app-routing.module.ts
  app/src/app/app.component.spec.ts
  app/src/app/app.component.ts
  app/src/app/app.module.ts
  app/src/app/services/api/api.service.spec.ts
  app/src/app/services/api/api.service.ts
  app/src/environments/environment.prod.ts
  app/src/environments/environment.ts
  app/src/main.ts
  app/src/polyfills.ts
  app/src/test.ts
Labels: frontend

#44 Frontend Resource service
  app/src/app/app.module.ts
  app/src/app/services/resource/resource.service.spec.ts
  app/src/app/services/resource/resource.service.ts
  src/sql/tables/NB_RESOURCE.csv
Labels: frontend

#45 Frontend User service
  app/src/app/app.module.ts
  app/src/app/services/book-condition/book-condition.interface.ts
  app/src/app/services/book/book.interface.ts
  app/src/app/services/department/department.interface.ts
  app/src/app/services/feedback/feedback.interface.ts
  app/src/app/services/message/message.interface.ts
  app/src/app/services/password-reset/password-reset.interface.ts
  app/src/app/services/referral/referral.interface.ts
  app/src/app/services/report/report.interface.ts
  app/src/app/services/resource/resource.interface.ts
  app/src/app/services/resource/resource.service.ts
  app/src/app/services/search-sort/search-sort.interface.ts
  app/src/app/services/user-interest/user-interest.interface.ts
  app/src/app/services/user/user.interface.ts
  app/src/app/services/user/user.service.spec.ts
  app/src/app/services/user/user.service.ts
  app/src/app/services/verify/verify.interface.ts
Labels: frontend

#46 Frontend Verify and Password Reset services
  app/src/app/app.module.ts
  app/src/app/services/password-reset/password-reset.service.spec.ts
  app/src/app/services/password-reset/password-reset.service.ts
  app/src/app/services/verify/verify.service.spec.ts
  app/src/app/services/verify/verify.service.ts
Labels: frontend

#47 Department and Book Condition services
  app/src/app/app.module.ts
  app/src/app/services/book-condition/book-condition.service.spec.ts
  app/src/app/services/book-condition/book-condition.service.ts
  app/src/app/services/department/department.service.spec.ts
  app/src/app/services/department/department.service.ts
Labels: frontend

#48 Implement frontend Book service
  app/src/app/app.module.ts
  app/src/app/services/book/book.interface.ts
  app/src/app/services/book/book.service.spec.ts
  app/src/app/services/book/book.service.ts
Labels: frontend

#49 Frontend Report and Message services
  app/src/app/app.module.ts
  app/src/app/services/message/message.service.spec.ts
  app/src/app/services/message/message.service.ts
  app/src/app/services/report/report.service.spec.ts
  app/src/app/services/report/report.service.ts
  src/controllers/message/message.controller.ts
Labels: frontend

#50 Frontend Search Sort and Feedback services
  app/src/app/app.module.ts
  app/src/app/services/feedback/feedback.service.spec.ts
  app/src/app/services/feedback/feedback.service.ts
  app/src/app/services/search-sort/search-sort.service.spec.ts
  app/src/app/services/search-sort/search-sort.service.ts
Labels: frontend

#51 Frontend User Interest and Referral services
  app/src/app/app.module.ts
  app/src/app/services/referral/referral.service.spec.ts
  app/src/app/services/referral/referral.service.ts
  app/src/app/services/user-interest/user-interest.service.spec.ts
  app/src/app/services/user-interest/user-interest.service.ts
Labels: frontend

#52 Admin script
  coverage/badge-branches.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  scripts/admin.py
  scripts/backup.py
Labels: script

#53 Add testing for resource strings
  coverage/badge-branches.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/services/resource/resource.service.spec.ts
Labels: testing

#54 Improve scripts
  .gitignore
  script.cmd
  script.sh
  scripts/admin.py
  scripts/backup.py
  scripts/env.py
Labels: script

#56 Implement header
  app/src/app/app.component.html
  app/src/app/app.component.scss
  app/src/app/app.module.ts
  app/src/app/components/header/header.component.html
  app/src/app/components/header/header.component.scss
  app/src/app/components/header/header.component.spec.ts
  app/src/app/components/header/header.component.ts
  app/src/app/services/user/user.service.ts
Labels: enhancement, frontend

#57 Add global styling
  app/src/styles.scss
Labels: frontend

#58 Home page
  app/angular.json
  app/src/app/app-routing.module.ts
  app/src/app/app.component.scss
  app/src/app/app.module.ts
  app/src/app/components/header/header.component.ts
  app/src/app/components/home/home.component.html
  app/src/app/components/home/home.component.scss
  app/src/app/components/home/home.component.spec.ts
  app/src/app/components/home/home.component.ts
  app/src/app/globals.ts
  app/src/assets/img/library.jpg
  app/src/globals.scss
  app/src/styles.scss
  src/decorators/query-boolean.decorator.ts
  src/decorators/query-number.decorator.ts
Labels: enhancement, frontend

#59 Register, login, and logout pages
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/home/home.component.html
  app/src/app/components/home/home.component.scss
  app/src/app/components/home/home.component.ts
  app/src/app/components/login/login.component.html
  app/src/app/components/login/login.component.scss
  app/src/app/components/login/login.component.spec.ts
  app/src/app/components/login/login.component.ts
  app/src/app/components/logout/logout.component.html
  app/src/app/components/logout/logout.component.scss
  app/src/app/components/logout/logout.component.spec.ts
  app/src/app/components/logout/logout.component.ts
  app/src/app/components/register/register.component.html
  app/src/app/components/register/register.component.scss
  app/src/app/components/register/register.component.spec.ts
  app/src/app/components/register/register.component.ts
  app/src/app/services/user/user.service.ts
  app/src/assets/img/backgrounds/home.jpg
  app/src/assets/img/backgrounds/login.jpg
  app/src/assets/img/backgrounds/register.jpg
  app/src/globals.scss
Labels: frontend

#60 Profile page
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/file-input/file-input.component.html
  app/src/app/components/file-input/file-input.component.scss
  app/src/app/components/file-input/file-input.component.spec.ts
  app/src/app/components/file-input/file-input.component.ts
  app/src/app/components/home/home.component.scss
  app/src/app/components/profile/profile.component.html
  app/src/app/components/profile/profile.component.scss
  app/src/app/components/profile/profile.component.spec.ts
  app/src/app/components/profile/profile.component.ts
  app/src/app/globals.ts
  app/src/app/services/report/report.service.ts
  app/src/app/services/user/user.interface.ts
  app/src/app/services/user/user.service.ts
  app/src/assets/img/backgrounds/profile.jpg
  app/src/globals.scss
  coverage/badge-branches.svg
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/controllers/report/report.controller.ts
  src/controllers/user/user.controller.ts
  src/main.ts
  src/services/report/report.service.spec.ts
  src/services/report/report.service.ts
Labels: enhancement, frontend

#61 Add site footer
  app/src/app/app.component.html
  app/src/app/app.component.scss
  app/src/app/app.module.ts
  app/src/app/components/footer/footer.component.html
  app/src/app/components/footer/footer.component.scss
  app/src/app/components/footer/footer.component.spec.ts
  app/src/app/components/footer/footer.component.ts
  app/src/app/components/home/home.component.html
  app/src/app/components/logout/logout.component.html
  app/src/app/components/profile/profile.component.html
  app/src/globals.scss
Labels: enhancement, frontend

#62 404 page
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/not-found/not-found.component.html
  app/src/app/components/not-found/not-found.component.scss
  app/src/app/components/not-found/not-found.component.spec.ts
  app/src/app/components/not-found/not-found.component.ts
  app/src/assets/img/backgrounds/not-found.jpg
Labels: frontend

#63 Open graph protocol
  app/src/assets/img/icons/icon-128x128.png
  app/src/assets/img/icons/icon-144x144.png
  app/src/assets/img/icons/icon-152x152.png
  app/src/assets/img/icons/icon-192x192.png
  app/src/assets/img/icons/icon-384x384.png
  app/src/assets/img/icons/icon-512x512.png
  app/src/assets/img/icons/icon-72x72.png
  app/src/assets/img/icons/icon-96x96.png
  app/src/index.html
  app/src/manifest.webmanifest
Labels: frontend

#64 Admin header link
  app/angular.json
  app/src/app/components/file-input/file-input.component.scss
  app/src/app/components/footer/footer.component.scss
  app/src/app/components/header/header.component.html
  app/src/app/components/header/header.component.scss
  app/src/app/components/header/header.component.ts
  app/src/app/components/logout/logout.component.scss
Labels: enhancement, frontend

#66 Verify and password reset page
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/password-reset/password-reset.component.html
  app/src/app/components/password-reset/password-reset.component.scss
  app/src/app/components/password-reset/password-reset.component.spec.ts
  app/src/app/components/password-reset/password-reset.component.ts
  app/src/app/components/verify/verify.component.html
  app/src/app/components/verify/verify.component.scss
  app/src/app/components/verify/verify.component.spec.ts
  app/src/app/components/verify/verify.component.ts
  app/src/app/services/password-reset/password-reset.service.ts
  app/src/assets/img/backgrounds/password-reset.jpg
  app/src/assets/img/backgrounds/verify.jpg
  app/src/globals.scss
  src/controllers/password-reset/password-reset.controller.ts
Labels: enhancement, frontend

#67 Update README
  README.md
Labels: documentation

#68 Fix README typos
  README.md
Labels: bug, frontend

#69 Book creation page
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/book-create/book-create.component.html
  app/src/app/components/book-create/book-create.component.scss
  app/src/app/components/book-create/book-create.component.spec.ts
  app/src/app/components/book-create/book-create.component.ts
  app/src/app/components/file-input/file-input.component.ts
  app/src/app/globals.ts
  app/src/assets/img/backgrounds/book-create.jpg
Labels: enhancement, frontend

#70 Book view page
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/book-view/book-view.component.html
  app/src/app/components/book-view/book-view.component.scss
  app/src/app/components/book-view/book-view.component.spec.ts
  app/src/app/components/book-view/book-view.component.ts
  app/src/app/components/dialog/dialog.component.html
  app/src/app/components/dialog/dialog.component.scss
  app/src/app/components/dialog/dialog.component.spec.ts
  app/src/app/components/dialog/dialog.component.ts
  app/src/app/components/header/header.component.html
  app/src/app/globals.ts
  app/src/assets/img/backgrounds/book-view.jpg
Labels: enhancement, frontend

#71 Book list component
  app/src/app/app.module.ts
  app/src/app/components/book-list/book-list.component.html
  app/src/app/components/book-list/book-list.component.scss
  app/src/app/components/book-list/book-list.component.spec.ts
  app/src/app/components/book-list/book-list.component.ts
  app/src/app/components/home/home.component.html
  app/src/app/components/profile/profile.component.html
  src/services/book/book.service.ts
Labels: enhancement, frontend

#72 Prefixes and suffixes in forms
  app/src/app/components/login/login.component.html
  app/src/app/components/login/login.component.ts
  app/src/app/components/register/register.component.html
  app/src/app/components/register/register.component.ts
  coverage/badge-branches.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/services/user/user.service.spec.ts
  src/services/user/user.service.ts
Labels: bug, enhancement, frontend, backend

#73 Unauthorized page
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/book-create/book-create.component.html
  app/src/app/components/book-create/book-create.component.ts
  app/src/app/components/profile/profile.component.html
  app/src/app/components/profile/profile.component.ts
  app/src/app/components/unauthorized/unauthorized.component.html
  app/src/app/components/unauthorized/unauthorized.component.scss
  app/src/app/components/unauthorized/unauthorized.component.spec.ts
  app/src/app/components/unauthorized/unauthorized.component.ts
  app/src/assets/img/backgrounds/unauthorized.jpg
Labels: enhancement, frontend

#75 Check cookie to determine login status
  app/src/app/services/user/user.service.ts
Labels: bug, enhancement, frontend

#76 Header menu
  app/src/app/app.module.ts
  app/src/app/components/book-list/book-list.component.ts
  app/src/app/components/header/header.component.html
  app/src/app/components/header/header.component.scss
  app/src/app/components/home/home.component.html
  app/src/app/components/home/home.component.ts
Labels: bug, enhancement, frontend

#78 Book edit page
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/book-edit/book-edit.component.html
  app/src/app/components/book-edit/book-edit.component.scss
  app/src/app/components/book-edit/book-edit.component.spec.ts
  app/src/app/components/book-edit/book-edit.component.ts
  app/src/app/components/book-view/book-view.component.html
  app/src/app/components/book-view/book-view.component.ts
  app/src/app/globals.ts
  app/src/app/services/book/book.interface.ts
  app/src/assets/img/backgrounds/book-edit.jpg
  src/controllers/book/book.controller.ts
  src/decorators/parameter.ts
  src/decorators/query-boolean.decorator.ts
  src/decorators/query-number.decorator.ts
  src/decorators/query-string.decorator.ts
  src/services/book/book.service.ts
Labels: enhancement, frontend, backend

#79 User referral system
  app/src/app/components/profile/profile.component.html
  app/src/app/components/profile/profile.component.ts
  src/services/referral/referral.service.ts
Labels: enhancement, frontend

#80 About page
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/about/about.component.html
  app/src/app/components/about/about.component.scss
  app/src/app/components/about/about.component.spec.ts
  app/src/app/components/about/about.component.ts
  app/src/assets/img/backgrounds/about.jpg
Labels: enhancement, frontend

#81 Feedback page
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/book-create/book-create.component.html
  app/src/app/components/book-edit/book-edit.component.html
  app/src/app/components/feedback/feedback.component.html
  app/src/app/components/feedback/feedback.component.scss
  app/src/app/components/feedback/feedback.component.spec.ts
  app/src/app/components/feedback/feedback.component.ts
  app/src/app/services/feedback/feedback.service.ts
  app/src/assets/img/backgrounds/feedback.jpg
Labels: enhancement, frontend
